version: '3.7'
services:
  server: 
    image: server-app
    ports:
      - 3000:3000
  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb_container
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb_container:27017/

volumes:
  mongodb_data_container:
